version: '1.1'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSGRES_USER=qa_user
      - POSGRES_PASSWORD=qa_pass
      - POSTGRES_DB=qa_db
    volumes: 
      - db_data:
      healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s      
  cache:
    image: redis:7-alpine

  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"    
